CE enabled: true
CE break explosion chance: 0.03125
CE torch explosion chance: 0.2
CE torch range: 2
CE explosion power: 3.0
CE explosion delay: 2

SW enabled: true
SW web chance: 1.0
SW web despawn time: 60

BN enabled: true

ZI enabled: true
ZI food damage: 5
ZI poison at foodlevel: 10
ZI cured at foodlevel: 20

SM chance: 0.1